apiVersion: apps/v1
kind: Deployment
metadata:
  name: argilla-server-deployment
  labels:
    app: argilla-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: argilla-server
  template:
    metadata:
      labels:
        app: argilla-server
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: role
                operator: In
                values:
                - backend
      initContainers:
        - name: wait-for-elasticsearch
          image: alpine/curl:latest
          command: [ "sh", "-c",
            "ELASTICSEARCH_URL='https://elastic:$(ELASTIC_PASSWORD)@elasticsearch-master:9200'; status_code=$(curl -s -k -o /dev/null -w '%{http_code}' $ELASTICSEARCH_URL);
          while [ $status_code -ne 200 ]; do sleep 5; status_code=$(curl -s -o /dev/null -w '%{http_code}' $ELASTICSEARCH_URL);
          echo Sleeping...; done; echo Elasticsearch Connected " ]
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-credentials
                  key: password
      containers:
        - name: argilla-server
          image: extralit-argilla-server
          ports:
            - containerPort: 6900
          resources:
            requests:
              cpu: "1"
            limits:
              cpu: "2"
          env:
            - name: ARGILLA_ELASTICSEARCH_HOST
              value: "elasticsearch-master:9200"
            - name: ARGILLA_AUTH_SECRET_KEY
              value: "CHANGE_ME"
            - name: ARGILLA_CORS_ORIGINS
              value: '["*", "argilla-frontend"]'
            - name: POSTGRES_HOST
              value: "main-db:5432"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: main-db
                  key: postgres-password
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-credentials
                  key: password
            - name: ARGILLA_ELASTICSEARCH_CA_PATH
              value: /usr/share/elasticsearch/config/certs/ca.crt
          volumeMounts:
            - name: elasticsearch-master-certs
              mountPath: /usr/share/elasticsearch/config/certs
      volumes:
        - name: elasticsearch-master-certs
          secret:
            secretName: elasticsearch-master-certs
      imagePullSecrets:
      - name: regcred