blank_issues_enabled: false
contact_links:
  - name: ðŸ—¯ Community Discussions
    url: https://join.slack.com/t/extralit/shared_invite/zt-2kt8t12r7-uFj0bZ5SPAOhRFkxP7ZQaQ
    about: Our Slack Community loves to discuss Extralit and scientific literature review topics
