global:
  storageClass: "k8s-storage-policy"

nameOverride: "main-db"
fullnameOverride: "main-db"

postgresql:
  persistence:
    enabled: true
    storageClass: "k8s-storage-policy"
    size: 2Gi
  backup:
    size: 1Gi
  nodeAffinity: 
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: role
          operator: In
          values:
          - backend

